before:
  - description: "Downloading HubSpot custom module discovery"
    commands:
      - mvn -B dependency:get -Dartifact=com.hubspot:BlazarModuleDiscovery:1.0-SNAPSHOT:jar:shaded -Dtransitive=false
      - mvn -B dependency:copy -Dartifact=com.hubspot:BlazarModuleDiscovery:1.0-SNAPSHOT:jar:shaded -DoutputDirectory=target

stepActivation:
  upload:
    branches: [master, dep-versions]
  notify:
    branches: [master, dep-versions]
