before:
  - description: "Downloading HubSpot custom module discovery"
    commands:
      - mvn -B dependency:get -Dartifact=com.hubspot:BlazarModuleDiscovery:1.0-staging-SNAPSHOT:jar:shaded -Dtransitive=false
      - mvn -B dependency:copy -Dartifact=com.hubspot:BlazarModuleDiscovery:1.0-staging-SNAPSHOT:jar:shaded -DoutputDirectory=target
      - rm -rf ~/.m2/repository

stepActivation:
  upload:
    branches: [hs-master, hs-staging]
  notify:
    branches: [hs-master, hs-staging]
