buildDeps:
  - node-0.12.7
  - hs-build-tools

cmds:
  - npm install
  - npm install bender-deps
  - ./node_modules/.bin/gulp lint
  - >
      BLAZAR_API_URL=https://bootstrap.hubteam.com/blazar/v1
      BLAZAR_APP_URI=https://tools.hubteam.com/blazar
      BLAZAR_STATIC_ROOT=https://static.hsappstatic.net/BlazarUI/static-1.$BUILD_NUMBER
      ./node_modules/.bin/gulp build
  - ./node_modules/.bin/bender-deps cdn-publish BlazarUI@1.$BUILD_NUMBER dist
  - CI_ENVIRONMENT=PROD publish-build-success --project BlazarUI --version static-1.$BUILD_NUMBER
