buildDeps:
  - node-0.12.7
  - hs-build-tools

cache:
  - $PWD/bower_components

steps:
  - description: "Installing dependencies"
    commands:
      - npm install
      - >
        if [ -d ./node_modules/bender-deps ]; then
          npm update bender-deps
        else
          npm install bender-deps
        fi
  - description: "Linting"
    commands:
      - ./node_modules/.bin/gulp lint
  - description: "Running gulp build"
    commands:
      - >
          BLAZAR_API_URL=https://private.hubapi.com/blazar/v2
          BLAZAR_APP_URI=/blazar
          BLAZAR_STATIC_ROOT=https://static.hsappstatic.net/BlazarUIv2/static-1.$BUILD_NUMBER
          BLAZAR_USERNAME_COOKIE='hs_tools_username'
          ./node_modules/.bin/gulp build
  - name: publish
    description: "Publishing to the CDN"
    activeByDefault: false
    commands:
      - ./node_modules/.bin/bender-deps cdn-publish BlazarUIv2@1.$BUILD_NUMBER dist
  - name: publish
    description: "Notifying deploy service"
    activeByDefault: false
    commands:
      - command: CI_ENVIRONMENT=PROD publish-build-success --project BlazarUIv2 --version static-1.$BUILD_NUMBER
        env:
          BOOTSTRAP_PROPERTIES_PATH: /usr/share/hubspot/internal/hubspot.bootstrap.properties      
          
stepActivation:
  publish:
    branches: [master]
