cache:
  - $PWD/node_modules
  - $PWD/bower_components

steps:
  - description: "Installing dependencies"
    commands:
      - npm install
      - >
        if [ -d ./node_modules/bender-deps ]; then
          npm update bender-deps
        else
          npm install bender-deps
        fi
  - description: "Linting"
    commands:
      - ./node_modules/.bin/gulp lint
  - description: "Running gulp build"
    commands:
      - ./node_modules/.bin/gulp build
  - name: publish
    description: "Publishing to the CDN"
    activeByDefault: false
    commands:
      - ./node_modules/.bin/bender-deps cdn-publish BlazarUIBeta@1.$BUILD_NUMBER dist
  - name: publish
    description: "Notifying deploy service"
    activeByDefault: false
    commands:
      - command: CI_ENVIRONMENT=PROD publish-build-success --project BlazarUIBeta --version static-1.$BUILD_NUMBER
        env:
          BOOTSTRAP_PROPERTIES_PATH: /usr/share/hubspot/internal/hubspot.bootstrap.properties      
          
stepActivation:
  publish:
    branches: [master]

buildpack:
  host: git.hubteam.com
  organization: HubSpot
  repository: blazar-ui-buildpack
  branch: master
