buildDeps:
  - node-0.12.7
  - hs-build-tools

cmds:
  - npm install
  - npm install bender-deps
  - ./node_modules/.bin/gulp lint
  - >
      BLAZAR_API_URL=https://bootstrap.hubteam.com/blazar/v2
      BLAZAR_APP_URI=/blazarv2
      BLAZAR_STATIC_ROOT=https://static.hsappstatic.net/BlazarUIv2/static-1.$BUILD_NUMBER
      ./node_modules/.bin/gulp build
  - ./node_modules/.bin/bender-deps cdn-publish BlazarUIv2@1.$BUILD_NUMBER dist
  - CI_ENVIRONMENT=PROD publish-build-success --project BlazarUIv2 --version static-1.$BUILD_NUMBER
