buildDeps:
  - node-0.12.7
  - hs-build-tools

steps:
  - description: "Installing dependencies"
    commands:
      - npm install
      - npm install bender-deps
  - description: "Linting"
    commands:
      - ./node_modules/.bin/gulp lint
  - description: "Running gulp build"
    commands:
      - >
          BLAZAR_API_URL=https://bootstrap.hubteam.com/blazar/v2
          BLAZAR_APP_URI=/blazarv2
          BLAZAR_STATIC_ROOT=https://static.hsappstatic.net/BlazarUIv2/static-1.$BUILD_NUMBER
          BLAZAR_USERNAME_COOKIE='hs_tools_username'
          ./node_modules/.bin/gulp build
  - description: "Publishing to the CDN"
    commands:
      - ./node_modules/.bin/bender-deps cdn-publish BlazarUIv2@1.$BUILD_NUMBER dist
  - description: "Notifying deploy service"
    commands:
      - command: CI_ENVIRONMENT=PROD publish-build-success --project BlazarUIv2 --version static-1.$BUILD_NUMBER
        env:
          BOOTSTRAP_PROPERTIES_PATH: /usr/share/hubspot/internal/hubspot.bootstrap.properties        
